name: CI/CD - Docker + ACR + ACI

on:
  push:
    branches: [main]

env:
  RESOURCE_GROUP: "Flask-App-Action-RG"
  IMAGE_NAME: "simple-devops-app"
  ACR_NAME: "flaskappactionacr"
  ACI_NAME: "flaskappactionaci"
  LOCATION: "centralus"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Tag Docker image
        run: |
          docker tag $IMAGE_NAME:latest $ACR_NAME.azurecr.io/$IMAGE_NAME:latest

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Push Docker image to ACR
        run: |
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest

      - name: Deploy to ACI
        run: |
          az container create \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.ACI_NAME }} \
            --image ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest \
            --cpu 1 \
            --memory 1 \
            --registry-login-server ${{ env.ACR_NAME }}.azurecr.io \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --dns-name-label ${{ env.ACI_NAME }}-af1n \
            --ports 80 \
            --os-type Linux \
            --location ${{ env.LOCATION }} \
            --restart-policy Always

